apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-api
  labels:
    app: counter-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-api
  template:
    metadata:
      labels:
        app: counter-api
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: counter-api
          # For Raspberry Pi, use ARM-compatible image
          image: ghcr.io/tluhk/counter-api:arm
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: NPM_CONFIG_LOGLEVEL
              value: "verbose"
            - name: NODE_PATH
              value: "/app"
            # Add MongoDB connection environment variables
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/counter"
            # Add CORS configuration
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:8080,https://*.github.io,http://192.168.*.*,https://github.com"
            - name: CORS_ALLOWED_METHODS
              value: "GET,POST,PUT,DELETE,OPTIONS"
            - name: CORS_ALLOWED_HEADERS
              value: "Content-Type,Authorization"
            - name: CORS_EXPOSED_HEADERS
              value: "Content-Range,X-Content-Range"
            - name: CORS_CREDENTIALS
              value: "true"
            - name: CORS_MAX_AGE
              value: "86400"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: counter-api
spec:
  selector:
    app: counter-api
  ports:
    - port: 3333 # Change this from 80 to 3333
      targetPort: 8080
  type: ClusterIP
