apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-api
  labels:
    app: counter-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-api
  template:
    metadata:
      labels:
        app: counter-api
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: counter-api
          # For Raspberry Pi, use ARM-compatible image
          image: ghcr.io/tluhk/counter-api:arm
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: NPM_CONFIG_LOGLEVEL
              value: "verbose"
            - name: NODE_PATH
              value: "/app"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: counter-api
spec:
  selector:
    app: counter-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
